# Generated by Django 4.2.4 on 2023-08-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100, verbose_name='razón social')),
                ('municipio', models.CharField(max_length=50, verbose_name='municipio')),
                ('cif', models.CharField(max_length=50, verbose_name='CIF')),
                ('direccion', models.CharField(max_length=50, verbose_name='dirección')),
                ('provincia', models.CharField(max_length=50, verbose_name='provincia')),
                ('inicio_contrato', models.DateField(verbose_name='inicio del contrato')),
                ('fin_contrato', models.DateField(verbose_name='final del contrato')),
                ('reconocimientos', models.IntegerField(verbose_name='reconocimientos contratados')),
            ],
        ),
    ]
