# Generated by Django 4.2.4 on 2023-08-30 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_agenda', models.DateField(verbose_name='inicio de citas')),
                ('fecha_final_agenda', models.DateField(verbose_name='final de citas')),
                ('numero_citas', models.IntegerField()),
                ('fecha_cita', models.DateField(verbose_name='final del contrato')),
                ('codigo', models.CharField(max_length=20)),
                ('razon_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cita', models.CharField(max_length=20)),
                ('fecha_cita', models.DateTimeField()),
                ('paciente', models.CharField(max_length=50)),
                ('realizada', models.BooleanField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.reservacita')),
                ('razon_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
