# Generated by Django 4.2.4 on 2023-09-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='numero_cita',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
