# Generated by Django 4.2.4 on 2023-08-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_cita_codigo_remove_reservacita_fecha_cita'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cita',
            managers=[
            ],
        ),
    ]
