# Generated by Django 4.2.4 on 2023-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_cita_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='razon_social',
            field=models.CharField(max_length=50),
        ),
    ]
