# Generated by Django 4.2.4 on 2023-08-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_cita_razon_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='razon_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
        ),
        migrations.AlterField(
            model_name='reservacita',
            name='razon_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.empresa'),
        ),
    ]
