# Generated by Django 4.2.4 on 2023-08-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_cita_razon_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='razon_social',
            field=models.CharField(max_length=100, verbose_name='razón social'),
        ),
        migrations.AlterField(
            model_name='reservacita',
            name='razon_social',
            field=models.CharField(max_length=100, verbose_name='razón social'),
        ),
    ]
