# Generated by Django 4.2.4 on 2023-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_cita_razon_social_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacita',
            name='fecha_final_agenda',
        ),
        migrations.AlterField(
            model_name='reservacita',
            name='fecha_inicio_agenda',
            field=models.DateField(verbose_name='fecha de la cita'),
        ),
    ]
